# Generated by Django 2.2.6 on 2019-10-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=128, verbose_name='命令')),
                ('host', models.CharField(default='106.54.230.101', max_length=128, verbose_name='主机')),
                ('time', models.DateTimeField(verbose_name='发出命令的时间')),
            ],
            options={
                'verbose_name': '命令表',
                'verbose_name_plural': '命令表',
            },
        ),
    ]
