# Generated by Django 2.2.6 on 2019-10-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, verbose_name='ip')),
                ('host_name', models.CharField(max_length=128, verbose_name='主机名')),
                ('os', models.CharField(max_length=128, verbose_name='操作系统')),
                ('cpu', models.CharField(max_length=128, verbose_name='cpu型号')),
                ('last_login_time', models.CharField(max_length=128, verbose_name='上次登录时间')),
                ('is_delete', models.BooleanField(verbose_name='删除标志')),
            ],
            options={
                'verbose_name': '主机表',
                'verbose_name_plural': '主机表',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
